name: Test

on: 
  push:
    branches-ignore:
      - main
      
jobs:
  test:
    name: Test, Lint, and Security Scan
    runs-on: ubuntu-latest
    env:
      GO_VERSION: '>=1.23.0'
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Go Unit Tests
        uses: ./.github/workflows/actions/go-test
        with:
          go-version: ${{ env.GO_VERSION }}
      
      - name: Go Lint
        uses: golangci/golangci-lint-action@v6.5.1 
      
      - name: Go Security Scans
        uses: securego/gosec@v2.22.2
        with: 
          args: -exclude-generated ./...
