name: Run Unit Tests and Scans

on: 
  push:
    branches-ignore:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    name: Test, Lint, and Security Scan
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repository
        id: checkout
        uses: actions/checkout@v4

      - name: Pull Go Version From .go-version File
        id: fetch-go-version
        run: |
          echo "GO_VERSION=$(cat .go-version)" >> $GITHUB_ENV
          echo "GOTOOLCHAIN=go$(cat .go-version)" >> $GITHUB_ENV

      - name: Run Go Unit Tests
        uses: ./.github/workflows/actions/go-test
        id: go-unit-tests
        with:
          go-version: ${{ env.GO_VERSION }}
      
      - name: Go Lint
        id: golint
        uses: golangci/golangci-lint-action@v7.0.0 
      
      - name: Go Security Scans
        uses: securego/gosec@v2.22.3
        id: gosec
        with: 
          args: -exclude-generated ./...
